### ISSUE TITLE
Make win condition tiles explicit 

### ISSUE THREAD

**Issue by bglw** [TruncateGame/Truncate#13]
Currently win condition tiles are calculated based on near or far edges. Win condition tiles should instead be part of the board (and thus level editor)

**Comment by BlakeMScurr** [comment]
Wondering how the UI for win condition tiles should work? Probably some kind of colour depending on whose win condition square it is. 

Also, how should it work in the level editor? We now have 3+ things you might mean by clicking on a square: delete it; make it player 1's win square; make it player 2's win square.
