### ISSUE TITLE
Create game rules struct

### ISSUE THREAD

**Issue by BlakeMScurr** [TruncateGame/Truncate#20]
- Boolean for truncation
- Boolean for fog of war
- Boolean for death match win condition

Surface this struct all the way to the client, and toggle actual game functionality based on its values.

**Comment by bglw** [comment]
Additionally

- Time allowance per player
- Overtime penalty action (`*` tile, destruction, ...)
- Overtime penalty interval
- Number of tiles in hand
- Letter distribution
  - Whether to remove tiles from the bag or just use it as a reference
- Turn-based / realtime
- `𝑥` for `len+𝑥` in winning battles
- Turn swapping on/off
- Maximum consecutive swaps
- Win condition as an enum (destination / elimination / points / ...)

**Comment by bglw** [comment]
One thing you'll have to wrangle with for this is the fuzzy boundary between the responsibilities of `server` and `core`.

Mainly, currently the fog of war rule is really enforced by server:
https://github.com/TruncateGame/Truncate/blob/dea796b1a2064560f29da4f763dbf51edfe18847/server/src/game_state.rs#L94-L105

But that should really move into a `game.get_board(player_index)` sorta thing.

**Comment by bglw** [comment]
Half implemented by #25, not yet complete.
