### ISSUE TITLE
Highlight tile validity on the board

### ISSUE THREAD

**Issue by bglw** [TruncateGame/Truncate#230]
Needs design. Leading idea is to only highlight tiles in _invalid_ words and let the rest be inferred.

**Comment by nathancahill** [comment]
I think this is the right approach. I'd suggest slightly fading the tiles in the invalid words. 50% between valid and the opacity you get when they are removed.

**Comment by bglw** [comment]
@nathancahill would love to hear any feedback on the latest version if you have played it! Closing this out as it was implemented a while ago but I forgot 😅
