### ISSUE TITLE
battles menu can't be immediately closed

### ISSUE THREAD

**Issue by marwahaha** [TruncateGame/Truncate#249]
in an ongoing game, opening the battles menu (i.e. clicking on the i icon). Then the button to close the battles menu (right arrow icon) is not clickable and has no effect for several seconds.

I sometimes open this menu and I want to close it right away and I can't, which is frustrating. Ideally I can just close the menu right away.

**Comment by bglw** [comment]
Thanks for the note! Tracking this in #241 so I'll close this issue, follow there for an update :)
