### ISSUE TITLE
Bug(?) in new rule for invalid attackers

### ISSUE THREAD

**Issue by MrZander** [TruncateGame/Truncate#254]
Hello,

The new rule to allow invalid attackers seems to have a bug when selecting the "strongest" attacker.
As you can see in the battle below, `REF` beat `OR`, despite it not being 2 characters longer.  Instead, it used the length of `OSFC` to determine the character length for the attack.
This feels like a bug, or at minimum, very misleading.

![Screenshot_20240412_234735_Brave](https://github.com/TruncateGame/Truncate/assets/1673352/f63301b2-d462-49e8-9aa9-616b42a412cd)

If this is intended, I'd suggest a different example than `ENOUGH` and `EEX` in the "What's New" tutorial.  Something that illustrates this behavior.

**Comment by bglw** [comment]
Ah! That does indeed look like a bug, thanks for pointing that out! ❤️ Will fix that asap.

**Comment by bglw** [comment]
That has made it's way through to the production instance now so you shouldn't see it past your next refresh. Thanks again! 😄
