### ISSUE TITLE
Tutorial incorrect on long vs short word battles

### ISSUE THREAD

**Issue by bcspragu** [TruncateGame/Truncate#286]
Hi there!

Big Truncate fan, am checking out the codebase in hopes of adding a pluggable AI system to it. The tutorial at HEAD (e.g. not the version live on `truncate.town`) is incorrect:

![Screenshot 2024-11-15 at 13-39-11 Truncate A word-based strategy game](https://github.com/user-attachments/assets/d2afb168-182c-4a91-9c6f-314861a22eb0)

![Screenshot 2024-11-15 at 13-39-26 Truncate A word-based strategy game](https://github.com/user-attachments/assets/5261958e-4196-4aeb-a84d-54155d76ed51)

The live version uses the words `ENORMOUS` and `PUNY`, which work as expected, but in the latest tutorial, your word (`LARGE`) actually gets destroyed because it's only one letter long than the shorter word (`TINY`).

If this is part of some larger game change (e.g. changing battle rules), feel free to ignore me! (Though shortening the length advantage to one would change the game pretty substantially)

EDIT: Looking at the copy on the next tutorial ("Defender's Advantage"), maybe the end goal is to change the length advantage to one.

**Comment by bcspragu** [comment]
Yeah, closing this out as the end state is definitely a state of one, codebase is just in an intermediate state, just saw https://github.com/TruncateGame/Truncate/issues/281

**Comment by bglw** [comment]
Good eye! This is a rule change that will land for everyone on their respective Sundays 😄 

You can see the changelog file here: https://github.com/TruncateGame/Truncate/blob/main/truncate_client/tutorials/update_02.yml

**Comment by bglw** [comment]
(If you change your system time to Sunday before opening your local build you'll be able to see the final state)

**Comment by bglw** [comment]
Actually, good find that in this latent state it is loading the future tutorial. Resolving 👀
