### ISSUE TITLE
Feedback from play test

### ISSUE THREAD

**Issue by BlakeMScurr** [TruncateGame/Truncate#37]
- Frequent error when playing a tile requiring refresh (should hunt down bug, as well as having an auto refresh) ![339546361_959781435033783_4183767522487366273_n](https://user-images.githubusercontent.com/18047446/231081083-261bae58-8b3d-4fdd-b797-81f52dcfd4f4.png)
 - Not immediately clear when turn changes (maybe some sound or flashing or something?)
 - Battle descriptions disappear on refresh
 - wildcard not a good default - doesn't end the game, and in fact can give strong defensive positions
 - make sure you're not allowed to keep swapping when you're in a strong position
 - negative seconds remaining

**Comment by bglw** [comment]
Issues opened for all relevant items
